name: itv

on:
  schedule:
    - cron: '0 10,16 * * *'
  push:
    branches:
      - cc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      #- name: Run itv_allm
       # run: python ${{ github.workspace }}/itv_allm.py

      - name: Run e
        run: python ${{ github.workspace }}/e.py
        
      #- name: Run b
      #  run: python ${{ github.workspace }}/b.py
        
      #- name: Run c
      #  run: python ${{ github.workspace }}/c.py

      #- name: Run itv
        #run: python ${{ github.workspace }}/itv.py
        
      - name: 提交更改
        run: |

          git config --local user.email "dwc1119@163.com"
          git config --local user.name "dwc1119"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f

